package com.nexxserve.nexxauth;

import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.resttestclient.TestRestTemplate;
import org.springframework.boot.resttestclient.autoconfigure.AutoConfigureTestRestTemplate;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.test.web.server.LocalManagementPort;
import org.springframework.boot.test.web.server.LocalServerPort;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * Verifies the production monitoring setup over real HTTP: actuator health and
 * info served on the separate management port, open without a token, plus the
 * liveness/readiness probe endpoints. Everything else stays hidden.
 *
 * Note: the management.* config below mirrors application.properties because
 * the test classpath shadows the main properties file; the main file remains
 * the source of truth for real deployments.
 */
@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.RANDOM_PORT,
        properties = "management.server.port=0")
@AutoConfigureTestRestTemplate
class ActuatorIntegrationTest {

    @LocalManagementPort
    private int managementPort;

    @LocalServerPort
    private int serverPort;

    @Autowired
    private TestRestTemplate restTemplate;

    @Test
    void healthIsOpenWithoutAuthOnManagementPort() {
        ResponseEntity<String> response = restTemplate.getForEntity(
                url(managementPort, "/actuator/health"), String.class);

        // Anonymous clients see only the overall status: with
        // show-details=when-authorized the component internals (datasource,
        // probes) are hidden from unauthenticated requests.
        assertThat(response.getStatusCode()).isEqualTo(HttpStatus.OK);
        assertThat(response.getBody())
                .contains("\"status\":\"UP\"")
                .doesNotContain("\"db\"")
                .doesNotContain("\"components\"");
    }

    @Test
    void infoExposesAppMetadataWithoutAuth() {
        ResponseEntity<String> response = restTemplate.getForEntity(
                url(managementPort, "/actuator/info"), String.class);

        assertThat(response.getStatusCode()).isEqualTo(HttpStatus.OK);
        assertThat(response.getBody())
                .contains("\"name\":\"nexxauth\"")
                .contains("\"version\":\"")
                .contains("auth backend")
                // build-info.properties generated by the buildInfo task
                .contains("\"build\"")
                .contains("\"artifact\":\"nexxauth\"");
    }

    @Test
    void livenessAndReadinessProbesAreAvailable() {
        ResponseEntity<String> liveness = restTemplate.getForEntity(
                url(managementPort, "/actuator/health/liveness"), String.class);
        assertThat(liveness.getStatusCode()).isEqualTo(HttpStatus.OK);
        assertThat(liveness.getBody()).contains("\"status\":\"UP\"");

        ResponseEntity<String> readiness = restTemplate.getForEntity(
                url(managementPort, "/actuator/health/readiness"), String.class);
        assertThat(readiness.getStatusCode()).isEqualTo(HttpStatus.OK);
        assertThat(readiness.getBody()).contains("\"status\":\"UP\"");
    }

    @Test
    void unexposedActuatorEndpointsStayHidden() {
        // Not exposed and not permitted: rejected by the security chain, so no
        // actuator data ever leaks from these paths.
        ResponseEntity<String> env = restTemplate.getForEntity(
                url(managementPort, "/actuator/env"), String.class);
        assertThat(env.getStatusCode()).isEqualTo(HttpStatus.UNAUTHORIZED);

        ResponseEntity<String> beans = restTemplate.getForEntity(
                url(managementPort, "/actuator/beans"), String.class);
        assertThat(beans.getStatusCode()).isEqualTo(HttpStatus.UNAUTHORIZED);
    }

    @Test
    void mainApiStillRequiresAuth() {
        // The security rules are unchanged on the main port: actuator health is
        // permitted, but API endpoints still demand a token.
        ResponseEntity<String> api = restTemplate.getForEntity(
                url(serverPort, "/auth/me"), String.class);
        assertThat(api.getStatusCode()).isEqualTo(HttpStatus.UNAUTHORIZED);
    }

    private String url(int port, String path) {
        return "http://localhost:" + port + path;
    }
}
