-- Clients are the external apps that talk to an organisation's API. A client
-- has a type (WEB/ANDROID/IOS/SERVER) that drives its access rules, and may
-- carry a static token (for auth-required clients), allowed CORS origins and
-- free-form settings. Deleting the organisation removes its clients.

CREATE TABLE organisation_clients (
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organisation_id        BIGINT NOT NULL,
    name                   VARCHAR(100) NOT NULL,
    client_type            VARCHAR(20) NOT NULL,
    require_authentication BOOLEAN NOT NULL DEFAULT FALSE,
    token_hash             VARCHAR(64),
    allowed_origins        VARCHAR(2000),
    enabled                BOOLEAN NOT NULL DEFAULT TRUE,
    settings               VARCHAR(4000),
    created_at             TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at             TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_organisation_clients_org_name UNIQUE (organisation_id, name),
    CONSTRAINT fk_organisation_clients_org FOREIGN KEY (organisation_id)
        REFERENCES organisations (id) ON DELETE CASCADE,
    CONSTRAINT chk_organisation_clients_type
        CHECK (client_type IN ('WEB', 'ANDROID', 'IOS', 'SERVER'))
);

CREATE INDEX idx_organisation_clients_org ON organisation_clients (organisation_id);
