-- Persisted log entries: queryable audit trail for security-relevant events.
-- Organisation is optional so platform-level events (e.g. platform login)
-- have no org association.

CREATE TABLE log_entries (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    platform_id     BIGINT       NOT NULL,
    organisation_id BIGINT,
    level           VARCHAR(10)  NOT NULL,
    event_type      VARCHAR(60)  NOT NULL,
    message         VARCHAR(2000) NOT NULL,
    actor           VARCHAR(255),
    ip              VARCHAR(45),
    request_id      VARCHAR(36),
    detail          VARCHAR(2000),
    created_at      TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at      TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_log_entries_platform FOREIGN KEY (platform_id) REFERENCES platforms (id),
    CONSTRAINT fk_log_entries_organisation FOREIGN KEY (organisation_id) REFERENCES organisations (id)
);

CREATE INDEX idx_log_entries_platform      ON log_entries (platform_id);
CREATE INDEX idx_log_entries_organisation  ON log_entries (organisation_id);
CREATE INDEX idx_log_entries_level         ON log_entries (level);
CREATE INDEX idx_log_entries_event_type    ON log_entries (event_type);
CREATE INDEX idx_log_entries_created_at    ON log_entries (created_at);
