-- Initial schema: platforms, platform_users, refresh_tokens.
-- Written in portable SQL (H2/PostgreSQL compatible) so tests can exercise it.

CREATE TABLE platforms (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       VARCHAR(120) NOT NULL,
    slug       VARCHAR(100) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_platforms_slug UNIQUE (slug)
);

CREATE TABLE platform_users (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    platform_id BIGINT NOT NULL,
    first_name  VARCHAR(100) NOT NULL,
    last_name   VARCHAR(100) NOT NULL,
    email       VARCHAR(255) NOT NULL,
    password    VARCHAR(100) NOT NULL,
    phone       VARCHAR(30),
    role        VARCHAR(20) NOT NULL,
    enabled     BOOLEAN NOT NULL DEFAULT TRUE,
    created_at  TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at  TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_platform_users_email UNIQUE (email),
    CONSTRAINT fk_platform_users_platform FOREIGN KEY (platform_id) REFERENCES platforms (id)
);

CREATE TABLE refresh_tokens (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token_hash       VARCHAR(64) NOT NULL,
    platform_user_id BIGINT NOT NULL,
    expires_at       TIMESTAMP WITH TIME ZONE NOT NULL,
    revoked_at       TIMESTAMP WITH TIME ZONE,
    created_at       TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at       TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_refresh_tokens_token_hash UNIQUE (token_hash),
    CONSTRAINT fk_refresh_tokens_user FOREIGN KEY (platform_user_id) REFERENCES platform_users (id)
);

CREATE INDEX idx_platform_users_platform ON platform_users (platform_id);
CREATE INDEX idx_refresh_tokens_user ON refresh_tokens (platform_user_id);
