-- Store daily health-score snapshots so the UI can show a trend arrow
-- (up / down / same) comparing today's score to ~7 days ago.

CREATE TABLE organisation_health_history (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organisation_id BIGINT       NOT NULL,
    score           INT          NOT NULL,
    user_count      INT          NOT NULL DEFAULT 0,
    active_sessions INT          NOT NULL DEFAULT 0,
    signing_keys    INT          NOT NULL DEFAULT 0,
    api_clients     INT          NOT NULL DEFAULT 0,
    snapshot_date   DATE         NOT NULL,
    created_at      TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at      TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_health_history_org FOREIGN KEY (organisation_id) REFERENCES organisations (id) ON DELETE CASCADE,
    CONSTRAINT uq_health_history_org_date UNIQUE (organisation_id, snapshot_date)
);

CREATE INDEX idx_health_history_org_date ON organisation_health_history (organisation_id, snapshot_date DESC);
