-- Link management: each registered origin for a client becomes a link with
-- per-link CORS and source-restriction settings.

CREATE TABLE organisation_client_links (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id     BIGINT NOT NULL,
    origin        VARCHAR(2000) NOT NULL,
    allow_cors    BOOLEAN NOT NULL DEFAULT TRUE,
    limit_source  BOOLEAN NOT NULL DEFAULT FALSE,
    created_at    TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at    TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_client_links_client FOREIGN KEY (client_id)
        REFERENCES organisation_clients (id) ON DELETE CASCADE
);

CREATE INDEX idx_client_links_client ON organisation_client_links (client_id);

-- Data migration: split comma-separated allowed_origins into individual rows.
-- Uses a recursive CTE that is compatible with both H2 and PostgreSQL.
INSERT INTO organisation_client_links (client_id, origin, allow_cors, limit_source, created_at, updated_at)
WITH RECURSIVE split(client_id, rest, origin, created_at, updated_at) AS (
    SELECT
        id,
        CASE WHEN POSITION(',' IN allowed_origins) > 0
             THEN SUBSTRING(allowed_origins FROM 1 FOR POSITION(',' IN allowed_origins) - 1)
             ELSE allowed_origins
        END,
        TRIM(CASE WHEN POSITION(',' IN allowed_origins) > 0
             THEN SUBSTRING(allowed_origins FROM 1 FOR POSITION(',' IN allowed_origins) - 1)
             ELSE allowed_origins
        END),
        created_at,
        updated_at
    FROM organisation_clients
    WHERE allowed_origins IS NOT NULL AND TRIM(allowed_origins) <> ''

    UNION ALL

    SELECT
        client_id,
        CASE WHEN POSITION(',' IN rest) > 0
             THEN SUBSTRING(rest FROM POSITION(',' IN rest) + 1)
             ELSE ''
        END,
        TRIM(CASE WHEN POSITION(',' IN rest) > 0
             THEN SUBSTRING(rest FROM 1 FOR POSITION(',' IN rest) - 1)
             ELSE rest
        END),
        created_at,
        updated_at
    FROM split
    WHERE rest <> '' AND POSITION(',' IN rest) > 0
)
SELECT client_id, origin, TRUE, FALSE, created_at, updated_at
FROM split
WHERE origin <> '';
