-- Organisations belong to a platform; the slug is unique within that platform.

CREATE TABLE organisations (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    platform_id BIGINT NOT NULL,
    name        VARCHAR(200) NOT NULL,
    slug        VARCHAR(100) NOT NULL,
    description VARCHAR(1000),
    created_at  TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at  TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_organisations_platform_slug UNIQUE (platform_id, slug),
    CONSTRAINT fk_organisations_platform FOREIGN KEY (platform_id) REFERENCES platforms (id)
);

CREATE INDEX idx_organisations_platform ON organisations (platform_id);
