-- Verification flows (OTP / magic link) delivered through nexxbotify.
-- Covers: per-org feature toggles, per-user verification state, and the
-- single-use, hashed verification values themselves.

-- Per-organisation verification feature toggles (extend organisation_auth_configs).
ALTER TABLE organisation_auth_configs ADD COLUMN email_verification_enabled BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE organisation_auth_configs ADD COLUMN phone_verification_enabled BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE organisation_auth_configs ADD COLUMN password_reset_enabled BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE organisation_auth_configs ADD COLUMN otp_login_enabled BOOLEAN NOT NULL DEFAULT FALSE;

-- Per-user verification state.
ALTER TABLE organisation_users ADD COLUMN email_verified_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE organisation_users ADD COLUMN phone_verified_at TIMESTAMP WITH TIME ZONE;

-- Single-use verification values. Only a SHA-256 digest (Base64, 44 chars) of
-- the raw code/link is stored; the raw value goes to the user (email/SMS) and
-- is never persisted.
CREATE TABLE organisation_verification_tokens (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organisation_id      BIGINT NOT NULL,
    organisation_user_id BIGINT,
    purpose              VARCHAR(30) NOT NULL,
    channel              VARCHAR(10) NOT NULL,
    delivery             VARCHAR(10) NOT NULL,
    identifier           VARCHAR(255) NOT NULL,
    token_hash           VARCHAR(64) NOT NULL,
    expires_at           TIMESTAMP WITH TIME ZONE NOT NULL,
    consumed_at          TIMESTAMP WITH TIME ZONE,
    attempts             INT NOT NULL DEFAULT 0,
    sent_at              TIMESTAMP WITH TIME ZONE NOT NULL,
    created_at           TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at           TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_verification_token_org FOREIGN KEY (organisation_id) REFERENCES organisations (id) ON DELETE CASCADE,
    CONSTRAINT fk_verification_token_user FOREIGN KEY (organisation_user_id) REFERENCES organisation_users (id) ON DELETE SET NULL
);

-- Lookup by (org, purpose, channel, identifier) for active tokens, and by user
-- for profile-driven flows.
CREATE INDEX idx_verification_tokens_active
    ON organisation_verification_tokens (organisation_id, purpose, channel, identifier, consumed_at, expires_at);
CREATE INDEX idx_verification_tokens_user
    ON organisation_verification_tokens (organisation_user_id, purpose, consumed_at);