-- Restructure organisation user emails and phone numbers to support multiple entries per user.
-- Each email and phone is tracked with its own verification status (verified_at) and primary flag (is_primary),
-- with global uniqueness enforced per organisation.

CREATE TABLE organisation_user_emails (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organisation_id      BIGINT NOT NULL,
    organisation_user_id BIGINT NOT NULL,
    email                VARCHAR(255) NOT NULL,
    is_primary           BOOLEAN NOT NULL DEFAULT FALSE,
    verified_at          TIMESTAMP WITH TIME ZONE,
    created_at           TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at           TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_org_user_emails_org FOREIGN KEY (organisation_id) REFERENCES organisations (id) ON DELETE CASCADE,
    CONSTRAINT fk_org_user_emails_user FOREIGN KEY (organisation_user_id) REFERENCES organisation_users (id) ON DELETE CASCADE,
    CONSTRAINT uk_org_user_emails_org_email UNIQUE (organisation_id, email)
);

CREATE INDEX idx_org_user_emails_user ON organisation_user_emails (organisation_user_id);
CREATE INDEX idx_org_user_emails_org_email ON organisation_user_emails (organisation_id, email);

CREATE TABLE organisation_user_phones (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organisation_id      BIGINT NOT NULL,
    organisation_user_id BIGINT NOT NULL,
    phone                VARCHAR(30) NOT NULL,
    is_primary           BOOLEAN NOT NULL DEFAULT FALSE,
    verified_at          TIMESTAMP WITH TIME ZONE,
    created_at           TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at           TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_org_user_phones_org FOREIGN KEY (organisation_id) REFERENCES organisations (id) ON DELETE CASCADE,
    CONSTRAINT fk_org_user_phones_user FOREIGN KEY (organisation_user_id) REFERENCES organisation_users (id) ON DELETE CASCADE,
    CONSTRAINT uk_org_user_phones_org_phone UNIQUE (organisation_id, phone)
);

CREATE INDEX idx_org_user_phones_user ON organisation_user_phones (organisation_user_id);
CREATE INDEX idx_org_user_phones_org_phone ON organisation_user_phones (organisation_id, phone);

-- Migrate existing email and phone data into the new dedicated tables.
INSERT INTO organisation_user_emails (organisation_id, organisation_user_id, email, is_primary, verified_at, created_at, updated_at)
SELECT organisation_id, id, email, TRUE, email_verified_at, created_at, updated_at
FROM organisation_users
WHERE email IS NOT NULL AND TRIM(email) <> '';

INSERT INTO organisation_user_phones (organisation_id, organisation_user_id, phone, is_primary, verified_at, created_at, updated_at)
SELECT organisation_id, id, phone, TRUE, phone_verified_at, created_at, updated_at
FROM organisation_users
WHERE phone IS NOT NULL AND TRIM(phone) <> '';

-- Drop old columns and constraints from organisation_users.
ALTER TABLE organisation_users DROP CONSTRAINT IF EXISTS uk_organisation_users_email;
ALTER TABLE organisation_users DROP CONSTRAINT IF EXISTS uk_organisation_users_phone;
ALTER TABLE organisation_users DROP COLUMN IF EXISTS email;
ALTER TABLE organisation_users DROP COLUMN IF EXISTS phone;
ALTER TABLE organisation_users DROP COLUMN IF EXISTS email_verified_at;
ALTER TABLE organisation_users DROP COLUMN IF EXISTS phone_verified_at;
