-- Organisation-level RBAC.
-- Permissions are fixed in the application (never edited); roles group them
-- per organisation; org users get roles (never direct permissions).

ALTER TABLE organisations ADD COLUMN use_email_as_username BOOLEAN NOT NULL DEFAULT FALSE;

CREATE TABLE organisation_roles (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organisation_id BIGINT NOT NULL,
    name            VARCHAR(100) NOT NULL,
    created_at      TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at      TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_organisation_roles_name UNIQUE (organisation_id, name),
    CONSTRAINT fk_organisation_roles_org FOREIGN KEY (organisation_id) REFERENCES organisations (id)
);

-- A role's permissions: a role may have zero rows here (no permissions).
CREATE TABLE organisation_role_permissions (
    organisation_role_id BIGINT NOT NULL,
    permission           VARCHAR(50) NOT NULL,
    CONSTRAINT pk_organisation_role_permissions PRIMARY KEY (organisation_role_id, permission),
    CONSTRAINT fk_org_role_permissions_role FOREIGN KEY (organisation_role_id) REFERENCES organisation_roles (id)
);

CREATE TABLE organisation_users (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organisation_id BIGINT NOT NULL,
    first_name      VARCHAR(100) NOT NULL,
    last_name       VARCHAR(100) NOT NULL,
    username        VARCHAR(100),
    email           VARCHAR(255),
    enabled         BOOLEAN NOT NULL DEFAULT TRUE,
    created_at      TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at      TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_organisation_users_username UNIQUE (organisation_id, username),
    CONSTRAINT uk_organisation_users_email UNIQUE (organisation_id, email),
    CONSTRAINT fk_organisation_users_org FOREIGN KEY (organisation_id) REFERENCES organisations (id)
);

-- A user can hold many roles; a role can belong to many users.
CREATE TABLE organisation_user_roles (
    organisation_user_id BIGINT NOT NULL,
    organisation_role_id BIGINT NOT NULL,
    CONSTRAINT pk_organisation_user_roles PRIMARY KEY (organisation_user_id, organisation_role_id),
    CONSTRAINT fk_org_user_roles_user FOREIGN KEY (organisation_user_id) REFERENCES organisation_users (id),
    CONSTRAINT fk_org_user_roles_role FOREIGN KEY (organisation_role_id) REFERENCES organisation_roles (id)
);

CREATE INDEX idx_organisation_roles_org ON organisation_roles (organisation_id);
CREATE INDEX idx_organisation_users_org ON organisation_users (organisation_id);
