-- Organisation-level authentication: org users get passwords and can log in
-- under their platform slug. Each organisation owns an RSA key pair used to
-- sign its own access tokens (independent of the platform-wide HS256 secret).

-- Org users that were created as managed data (no auth) have NULL passwords and
-- simply cannot log in until one is set.
ALTER TABLE organisation_users ADD COLUMN password_hash VARCHAR(255);

-- Per-organisation signing keys. kid identifies the key in the JWT header so
-- verification can pick the right key after rotation; keys are kept (active
-- flag) so tokens signed with a retired key still verify until they expire.
CREATE TABLE organisation_signing_keys (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organisation_id BIGINT NOT NULL,
    kid             VARCHAR(64) NOT NULL,
    public_key      TEXT NOT NULL,
    private_key     TEXT NOT NULL,
    active          BOOLEAN NOT NULL DEFAULT TRUE,
    created_at      TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at      TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_org_signing_keys_kid UNIQUE (kid),
    CONSTRAINT fk_org_signing_keys_org FOREIGN KEY (organisation_id) REFERENCES organisations (id)
);
CREATE INDEX idx_org_signing_keys_org ON organisation_signing_keys (organisation_id);

-- Rotating refresh tokens for organisation users (mirror of refresh_tokens).
CREATE TABLE organisation_refresh_tokens (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token_hash           VARCHAR(64) NOT NULL,
    organisation_user_id BIGINT NOT NULL,
    expires_at           TIMESTAMP WITH TIME ZONE NOT NULL,
    revoked_at           TIMESTAMP WITH TIME ZONE,
    created_at           TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at           TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_org_refresh_tokens_token_hash UNIQUE (token_hash),
    CONSTRAINT fk_org_refresh_tokens_user FOREIGN KEY (organisation_user_id) REFERENCES organisation_users (id)
);
CREATE INDEX idx_org_refresh_tokens_user ON organisation_refresh_tokens (organisation_user_id);
