-- Organisation-level authentication configuration. This governs how org users
-- authenticate (auth type) and the password rules new passwords must follow:
-- min/max length, expiration, and history (cannot reuse the last N passwords).
-- It is organisation-scoped and never applies to the platform auth flow.

-- One config row per organisation (created lazily for orgs created before this
-- migration by OrganisationAuthConfigService; here we backfill existing orgs).
CREATE TABLE organisation_auth_configs (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organisation_id         BIGINT NOT NULL,
    auth_type               VARCHAR(30) NOT NULL DEFAULT 'PASSWORD',
    password_min_length     INT NOT NULL DEFAULT 8,
    password_max_length     INT NOT NULL DEFAULT 72,
    password_expiration_days INT NOT NULL DEFAULT 0,
    password_history_count  INT NOT NULL DEFAULT 0,
    created_at              TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at              TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_org_auth_configs_org UNIQUE (organisation_id),
    CONSTRAINT fk_org_auth_configs_org FOREIGN KEY (organisation_id) REFERENCES organisations (id) ON DELETE CASCADE
);

-- Backfill: every existing organisation gets the default config.
INSERT INTO organisation_auth_configs (organisation_id, created_at, updated_at)
SELECT id, now(), now() FROM organisations;

-- Per-user auth state: auth_type is NULL until an auth method is configured
-- (a user created without a password has no auth and cannot log in).
ALTER TABLE organisation_users ADD COLUMN auth_type VARCHAR(30);
ALTER TABLE organisation_users ADD COLUMN password_changed_at TIMESTAMP WITH TIME ZONE;

-- Existing users that already have a password keep password auth; treat their
-- stored created/updated time as the (unknown) change time so expiration
-- policies start counting from now-ish instead of from NULL.
UPDATE organisation_users
SET auth_type = 'PASSWORD',
    password_changed_at = COALESCE(updated_at, created_at)
WHERE password_hash IS NOT NULL;

-- Password history: one row per previous password hash, used to enforce
-- "cannot reuse the last N passwords". Kept alongside the current hash.
CREATE TABLE organisation_password_history (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organisation_user_id BIGINT NOT NULL,
    password_hash        VARCHAR(255) NOT NULL,
    created_at           TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at           TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_org_password_history_user FOREIGN KEY (organisation_user_id) REFERENCES organisation_users (id) ON DELETE CASCADE
);
CREATE INDEX idx_org_password_history_user ON organisation_password_history (organisation_user_id);
