-- Organisation-level session settings. This governs how long org access and
-- refresh tokens live and how many concurrent sessions (active refresh tokens)
-- a single org user may hold. One row per organisation (created lazily for
-- orgs created before this migration; backfilled below). It is
-- organisation-scoped and never applies to the platform auth flow.

CREATE TABLE organisation_session_settings (
    id                        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organisation_id           BIGINT NOT NULL,
    access_token_ttl_seconds  BIGINT NOT NULL DEFAULT 900,
    refresh_token_ttl_seconds BIGINT NOT NULL DEFAULT 604800,
    max_sessions_per_user     INT NOT NULL DEFAULT 5,
    created_at                TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at                TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_org_session_settings_org UNIQUE (organisation_id),
    CONSTRAINT fk_org_session_settings_org FOREIGN KEY (organisation_id) REFERENCES organisations (id) ON DELETE CASCADE
);

-- Backfill: every existing organisation gets the default settings.
INSERT INTO organisation_session_settings (organisation_id, created_at, updated_at)
SELECT id, now(), now() FROM organisations;

-- Sessions evicted by the concurrent-session limit are marked separately from
-- rotation revocation: an evicted token is invalid (401) but does NOT trigger
-- the family-wide theft detection that a replayed rotated token does, so an
-- old device's stale refresh cannot kill the user's newer sessions.
ALTER TABLE organisation_refresh_tokens ADD COLUMN evicted_at TIMESTAMP WITH TIME ZONE;
