-- Organisation-defined custom user fields. Each org can define extra per-user
-- attributes (e.g. employee-id, department). A field has a fixed value type
-- (string/number/boolean/date) and may be enabled as an alternative login
-- identifier alongside username/email. Values live per user+field in
-- organisation_user_field_values; whether a field is used for login is a
-- config-level flag and is never echoed on the user objects themselves.

CREATE TABLE organisation_user_fields (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organisation_id BIGINT NOT NULL,
    field_key       VARCHAR(100) NOT NULL,
    label           VARCHAR(100) NOT NULL,
    field_type      VARCHAR(20) NOT NULL,
    login_enabled   BOOLEAN NOT NULL DEFAULT FALSE,
    created_at      TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at      TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_org_user_fields_key UNIQUE (organisation_id, field_key),
    CONSTRAINT fk_org_user_fields_org FOREIGN KEY (organisation_id) REFERENCES organisations (id) ON DELETE CASCADE
);

CREATE TABLE organisation_user_field_values (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         BIGINT NOT NULL,
    organisation_id BIGINT NOT NULL,
    field_key       VARCHAR(100) NOT NULL,
    field_value     VARCHAR(255) NOT NULL,
    created_at      TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at      TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_user_field_values_key UNIQUE (user_id, field_key),
    CONSTRAINT fk_user_field_values_user FOREIGN KEY (user_id) REFERENCES organisation_users (id) ON DELETE CASCADE,
    CONSTRAINT fk_user_field_values_org FOREIGN KEY (organisation_id) REFERENCES organisations (id) ON DELETE CASCADE
);

-- Fast login-by-field lookup: (organisation, field key, normalized value).
-- Uniqueness of values for login-enabled fields is enforced at write time.
CREATE INDEX idx_user_field_values_login
    ON organisation_user_field_values (organisation_id, field_key, field_value);
